var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/tools/sing-sync-manager/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__67775a22._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_f72be63d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__49ca08b5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f68cf2f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__ca19f1a8._.js")
R.c("server/chunks/ssr/_f9947ac4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_981dc6eb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_tools_sing-sync-manager_page_actions_b0af6d8c.js")
R.m(86367)
module.exports=R.m(86367).exports
