// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(result)/result-page/self-assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/result-page/self-assessment">> = Specific
  const handler = {} as typeof import("../../src/app/(result)/result-page/self-assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(result)/result-page/sing-training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/result-page/sing-training">> = Specific
  const handler = {} as typeof import("../../src/app/(result)/result-page/sing-training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(result)/result-page/speech-rehab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/result-page/speech-rehab">> = Specific
  const handler = {} as typeof import("../../src/app/(result)/result-page/speech-rehab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/mypage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/mypage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/lingo/association-clear/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/lingo/association-clear">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/lingo/association-clear/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/lingo/balloon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/lingo/balloon">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/lingo/balloon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/lingo/memory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/lingo/memory">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/lingo/memory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/lingo/sentence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/lingo/sentence">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/lingo/sentence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/lingo/tetris/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/lingo/tetris">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/lingo/tetris/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/lingo/word-assemble/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/lingo/word-assemble">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/lingo/word-assemble/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/lingo/word-select/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/lingo/word-select">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/lingo/word-select/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/sing-training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/sing-training">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/sing-training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/step-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/step-1">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/step-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/step-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/step-2">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/step-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/step-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/step-3">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/step-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/step-4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/step-4">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/step-4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/step-5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/step-5">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/step-5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/programs/step-6/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/step-6">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/programs/step-6/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/select-page/game-mode/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-page/game-mode">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/select-page/game-mode/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/select-page/game-mode/stage/[stageId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-page/game-mode/stage/[stageId]">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/select-page/game-mode/stage/[stageId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/select-page/mode/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-page/mode">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/select-page/mode/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/select-page/self-assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-page/self-assessment">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/select-page/self-assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/select-page/sing-training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-page/sing-training">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/select-page/sing-training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(training)/select-page/speech-rehab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-page/speech-rehab">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/select-page/speech-rehab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/docs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/docs/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/docs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/find-id/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/find-id">> = Specific
  const handler = {} as typeof import("../../src/app/find-id/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/link-care/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/link-care">> = Specific
  const handler = {} as typeof import("../../src/app/link-care/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/organization-register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization-register">> = Specific
  const handler = {} as typeof import("../../src/app/organization-register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/patients/[patientId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/patients/[patientId]">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/patients/[patientId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/patients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/patients">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/patients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/results">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/system/evaluation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/system/evaluation">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/system/evaluation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/system/organizations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/system/organizations">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/system/organizations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/system">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/system/provision/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapist/system/provision">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/system/provision/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/admin-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/admin-reports">> = Specific
  const handler = {} as typeof import("../../src/app/tools/admin-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/sing-sync-manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/sing-sync-manager">> = Specific
  const handler = {} as typeof import("../../src/app/tools/sing-sync-manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/training-usage-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/training-usage-admin">> = Specific
  const handler = {} as typeof import("../../src/app/tools/training-usage-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/training-usage-timeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/training-usage-timeline">> = Specific
  const handler = {} as typeof import("../../src/app/tools/training-usage-timeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/organizations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/organizations">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/organizations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/patient-links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/patient-links">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/patient-links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/therapists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/therapists">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/therapists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/check-login-id/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/check-login-id">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/check-login-id/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/dev-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/dev-login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/dev-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/find-login-id/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/find-login-id">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/find-login-id/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client-storage-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client-storage-sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/client-storage-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clinical-results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clinical-results">> = Specific
  const handler = {} as typeof import("../../src/app/api/clinical-results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/evaluation-samples/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evaluation-samples">> = Specific
  const handler = {} as typeof import("../../src/app/api/evaluation-samples/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kwab/final-result/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kwab/final-result">> = Specific
  const handler = {} as typeof import("../../src/app/api/kwab/final-result/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/access">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/complete-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/complete-upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/complete-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/init-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/init-upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/init-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onboarding/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/onboarding/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organization-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/organization-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organizations/[organizationId]/therapists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[organizationId]/therapists">> = Specific
  const handler = {} as typeof import("../../src/app/api/organizations/[organizationId]/therapists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organizations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations">> = Specific
  const handler = {} as typeof import("../../src/app/api/organizations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/patient/link-care/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/patient/link-care">> = Specific
  const handler = {} as typeof import("../../src/app/api/patient/link-care/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/proxy/stt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy/stt">> = Specific
  const handler = {} as typeof import("../../src/app/api/proxy/stt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/proxy/voice-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy/voice-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/api/proxy/voice-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/security-audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-audit">> = Specific
  const handler = {} as typeof import("../../src/app/api/security-audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sing-results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sing-results">> = Specific
  const handler = {} as typeof import("../../src/app/api/sing-results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/therapist/reports/note/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/therapist/reports/note">> = Specific
  const handler = {} as typeof import("../../src/app/api/therapist/reports/note/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/therapist/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/therapist/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/therapist/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/therapist/system/ai-evaluation-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/therapist/system/ai-evaluation-export">> = Specific
  const handler = {} as typeof import("../../src/app/api/therapist/system/ai-evaluation-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/therapist/system/vnv-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/therapist/system/vnv-export">> = Specific
  const handler = {} as typeof import("../../src/app/api/therapist/system/vnv-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training-events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training-events">> = Specific
  const handler = {} as typeof import("../../src/app/api/training-events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(training)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(training)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/therapist/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/therapist">> = Specific
  const handler = {} as typeof import("../../src/app/therapist/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
