var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/link-care/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__8ae68a78._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_275714e8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__49ca08b5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f68cf2f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__ca19f1a8._.js")
R.c("server/chunks/ssr/_f9947ac4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_981dc6eb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_link-care_page_actions_c9cf3fb8.js")
R.m(25000)
module.exports=R.m(25000).exports
