// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/docs/[slug]" | "/find-id" | "/link-care" | "/mypage" | "/organization-register" | "/programs/lingo/association-clear" | "/programs/lingo/balloon" | "/programs/lingo/memory" | "/programs/lingo/sentence" | "/programs/lingo/tetris" | "/programs/lingo/word-assemble" | "/programs/lingo/word-select" | "/programs/sing-training" | "/programs/step-1" | "/programs/step-2" | "/programs/step-3" | "/programs/step-4" | "/programs/step-5" | "/programs/step-6" | "/report" | "/reset-password" | "/result-page/self-assessment" | "/result-page/sing-training" | "/result-page/speech-rehab" | "/select-page/game-mode" | "/select-page/game-mode/stage/[stageId]" | "/select-page/mode" | "/select-page/self-assessment" | "/select-page/sing-training" | "/select-page/speech-rehab" | "/signup" | "/therapist" | "/therapist/patients" | "/therapist/patients/[patientId]" | "/therapist/results" | "/therapist/system" | "/therapist/system/evaluation" | "/therapist/system/organizations" | "/therapist/system/provision" | "/tools/admin-reports" | "/tools/sing-sync-manager" | "/tools/training-usage-admin" | "/tools/training-usage-timeline"
type AppRouteHandlerRoutes = "/api/admin/organizations" | "/api/admin/patient-links" | "/api/admin/reports" | "/api/admin/therapists" | "/api/auth/check-login-id" | "/api/auth/dev-login" | "/api/auth/find-login-id" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/reset-password" | "/api/auth/session" | "/api/auth/signup" | "/api/client-storage-sync" | "/api/clinical-results" | "/api/evaluation-samples" | "/api/history/me" | "/api/kwab/final-result" | "/api/media/access" | "/api/media/complete-upload" | "/api/media/init-upload" | "/api/media/upload" | "/api/onboarding/status" | "/api/organization-requests" | "/api/organizations" | "/api/organizations/[organizationId]/therapists" | "/api/patient/link-care" | "/api/proxy/stt" | "/api/proxy/voice-analysis" | "/api/security-audit" | "/api/sing-results" | "/api/therapist/reports" | "/api/therapist/reports/note" | "/api/therapist/system/ai-evaluation-export" | "/api/therapist/system/vnv-export" | "/api/training-events"
type PageRoutes = never
type LayoutRoutes = "/" | "/therapist"
type RedirectRoutes = "/brain-sing" | "/mode-select" | "/rehab" | "/result" | "/result-rehab" | "/select" | "/select-sing" | "/step-1" | "/step-2" | "/step-3" | "/step-4" | "/step-5" | "/step-6"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/docs/[slug]": { "slug": string; }
  "/api/admin/organizations": {}
  "/api/admin/patient-links": {}
  "/api/admin/reports": {}
  "/api/admin/therapists": {}
  "/api/auth/check-login-id": {}
  "/api/auth/dev-login": {}
  "/api/auth/find-login-id": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/reset-password": {}
  "/api/auth/session": {}
  "/api/auth/signup": {}
  "/api/client-storage-sync": {}
  "/api/clinical-results": {}
  "/api/evaluation-samples": {}
  "/api/history/me": {}
  "/api/kwab/final-result": {}
  "/api/media/access": {}
  "/api/media/complete-upload": {}
  "/api/media/init-upload": {}
  "/api/media/upload": {}
  "/api/onboarding/status": {}
  "/api/organization-requests": {}
  "/api/organizations": {}
  "/api/organizations/[organizationId]/therapists": { "organizationId": string; }
  "/api/patient/link-care": {}
  "/api/proxy/stt": {}
  "/api/proxy/voice-analysis": {}
  "/api/security-audit": {}
  "/api/sing-results": {}
  "/api/therapist/reports": {}
  "/api/therapist/reports/note": {}
  "/api/therapist/system/ai-evaluation-export": {}
  "/api/therapist/system/vnv-export": {}
  "/api/training-events": {}
  "/brain-sing": {}
  "/find-id": {}
  "/link-care": {}
  "/mode-select": {}
  "/mypage": {}
  "/organization-register": {}
  "/programs/lingo/association-clear": {}
  "/programs/lingo/balloon": {}
  "/programs/lingo/memory": {}
  "/programs/lingo/sentence": {}
  "/programs/lingo/tetris": {}
  "/programs/lingo/word-assemble": {}
  "/programs/lingo/word-select": {}
  "/programs/sing-training": {}
  "/programs/step-1": {}
  "/programs/step-2": {}
  "/programs/step-3": {}
  "/programs/step-4": {}
  "/programs/step-5": {}
  "/programs/step-6": {}
  "/rehab": {}
  "/report": {}
  "/reset-password": {}
  "/result": {}
  "/result-page/self-assessment": {}
  "/result-page/sing-training": {}
  "/result-page/speech-rehab": {}
  "/result-rehab": {}
  "/select": {}
  "/select-page/game-mode": {}
  "/select-page/game-mode/stage/[stageId]": { "stageId": string; }
  "/select-page/mode": {}
  "/select-page/self-assessment": {}
  "/select-page/sing-training": {}
  "/select-page/speech-rehab": {}
  "/select-sing": {}
  "/signup": {}
  "/step-1": {}
  "/step-2": {}
  "/step-3": {}
  "/step-4": {}
  "/step-5": {}
  "/step-6": {}
  "/therapist": {}
  "/therapist/patients": {}
  "/therapist/patients/[patientId]": { "patientId": string; }
  "/therapist/results": {}
  "/therapist/system": {}
  "/therapist/system/evaluation": {}
  "/therapist/system/organizations": {}
  "/therapist/system/provision": {}
  "/tools/admin-reports": {}
  "/tools/sing-sync-manager": {}
  "/tools/training-usage-admin": {}
  "/tools/training-usage-timeline": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/therapist": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
